
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "test-objects-chart.fullname" . }}
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "test-objects-chart.fullname" . }}
  targetCPUUtilizationPercentage: 50
